namespace PersonalVicenteLeon.Ventanas
{
    partial class Instituto
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Instituto));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties73 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties74 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties75 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties76 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties77 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties78 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties79 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties80 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties81 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties82 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties83 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties84 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties85 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties86 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties87 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties88 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            this.panelUsuarios = new Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel();
            this.dropFinaciamiento = new Bunifu.UI.WinForms.BunifuDropdown();
            this.panel2 = new System.Windows.Forms.Panel();
            this.lblId = new System.Windows.Forms.Label();
            this.btnVolver = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnGuardarCambios = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtProvincia = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtCorreo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtTelefono = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtZona = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDireccion = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtCanton = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtParroquia = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtCodIess = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtNombre = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.dataGridUsuarios = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.eliminar = new System.Windows.Forms.DataGridViewImageColumn();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btnNuevo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.panelUsuarios.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridUsuarios)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            // 
            // panelUsuarios
            // 
            this.panelUsuarios.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.panelUsuarios.BackColor = System.Drawing.Color.White;
            this.panelUsuarios.BorderColor = System.Drawing.Color.Gainsboro;
            this.panelUsuarios.Controls.Add(this.dropFinaciamiento);
            this.panelUsuarios.Controls.Add(this.panel2);
            this.panelUsuarios.Controls.Add(this.btnVolver);
            this.panelUsuarios.Controls.Add(this.btnGuardarCambios);
            this.panelUsuarios.Controls.Add(this.btnGuardar);
            this.panelUsuarios.Controls.Add(this.txtProvincia);
            this.panelUsuarios.Controls.Add(this.txtCorreo);
            this.panelUsuarios.Controls.Add(this.txtTelefono);
            this.panelUsuarios.Controls.Add(this.txtZona);
            this.panelUsuarios.Controls.Add(this.txtDireccion);
            this.panelUsuarios.Controls.Add(this.txtCanton);
            this.panelUsuarios.Controls.Add(this.txtParroquia);
            this.panelUsuarios.Controls.Add(this.txtCodIess);
            this.panelUsuarios.Controls.Add(this.txtNombre);
            this.panelUsuarios.Controls.Add(this.label2);
            this.panelUsuarios.Controls.Add(this.label6);
            this.panelUsuarios.Controls.Add(this.label5);
            this.panelUsuarios.Controls.Add(this.label7);
            this.panelUsuarios.Controls.Add(this.label4);
            this.panelUsuarios.Controls.Add(this.label3);
            this.panelUsuarios.Controls.Add(this.label8);
            this.panelUsuarios.Controls.Add(this.label14);
            this.panelUsuarios.Controls.Add(this.label1);
            this.panelUsuarios.Controls.Add(this.label10);
            this.panelUsuarios.Location = new System.Drawing.Point(86, 92);
            this.panelUsuarios.Margin = new System.Windows.Forms.Padding(4);
            this.panelUsuarios.Name = "panelUsuarios";
            this.panelUsuarios.PanelColor = System.Drawing.Color.Empty;
            this.panelUsuarios.ShadowDept = 2;
            this.panelUsuarios.ShadowTopLeftVisible = false;
            this.panelUsuarios.Size = new System.Drawing.Size(1252, 573);
            this.panelUsuarios.TabIndex = 7;
            // 
            // dropFinaciamiento
            // 
            this.dropFinaciamiento.BackColor = System.Drawing.Color.White;
            this.dropFinaciamiento.BorderRadius = 1;
            this.dropFinaciamiento.Color = System.Drawing.Color.DodgerBlue;
            this.dropFinaciamiento.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.dropFinaciamiento.DisabledColor = System.Drawing.Color.Gray;
            this.dropFinaciamiento.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.dropFinaciamiento.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thick;
            this.dropFinaciamiento.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dropFinaciamiento.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.dropFinaciamiento.FillDropDown = false;
            this.dropFinaciamiento.FillIndicator = false;
            this.dropFinaciamiento.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dropFinaciamiento.ForeColor = System.Drawing.Color.Black;
            this.dropFinaciamiento.FormattingEnabled = true;
            this.dropFinaciamiento.Icon = null;
            this.dropFinaciamiento.IndicatorColor = System.Drawing.Color.DodgerBlue;
            this.dropFinaciamiento.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.dropFinaciamiento.ItemBackColor = System.Drawing.Color.White;
            this.dropFinaciamiento.ItemBorderColor = System.Drawing.Color.White;
            this.dropFinaciamiento.ItemForeColor = System.Drawing.Color.Purple;
            this.dropFinaciamiento.ItemHeight = 26;
            this.dropFinaciamiento.ItemHighLightColor = System.Drawing.Color.Thistle;
            this.dropFinaciamiento.Items.AddRange(new object[] {
            "SELECCIONE...",
            "PUBLICO",
            "PRIVADO"});
            this.dropFinaciamiento.Location = new System.Drawing.Point(64, 350);
            this.dropFinaciamiento.Name = "dropFinaciamiento";
            this.dropFinaciamiento.Size = new System.Drawing.Size(271, 32);
            this.dropFinaciamiento.TabIndex = 6;
            this.dropFinaciamiento.Text = "SELECCIONE...";
            this.dropFinaciamiento.SelectedIndexChanged += new System.EventHandler(this.dropFinaciamiento_SelectedIndexChanged);
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.lblId);
            this.panel2.Location = new System.Drawing.Point(29, 53);
            this.panel2.Margin = new System.Windows.Forms.Padding(4);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(10, 10);
            this.panel2.TabIndex = 5;
            // 
            // lblId
            // 
            this.lblId.AutoSize = true;
            this.lblId.Location = new System.Drawing.Point(11, 111);
            this.lblId.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblId.Name = "lblId";
            this.lblId.Size = new System.Drawing.Size(54, 17);
            this.lblId.TabIndex = 4;
            this.lblId.Text = "label12";
            // 
            // btnVolver
            // 
            this.btnVolver.AllowToggling = false;
            this.btnVolver.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnVolver.AnimationSpeed = 200;
            this.btnVolver.AutoGenerateColors = false;
            this.btnVolver.BackColor = System.Drawing.Color.Transparent;
            this.btnVolver.BackColor1 = System.Drawing.Color.Red;
            this.btnVolver.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVolver.BackgroundImage")));
            this.btnVolver.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVolver.ButtonText = "Volver";
            this.btnVolver.ButtonTextMarginLeft = 0;
            this.btnVolver.ColorContrastOnClick = 45;
            this.btnVolver.ColorContrastOnHover = 45;
            this.btnVolver.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnVolver.CustomizableEdges = borderEdges5;
            this.btnVolver.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVolver.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnVolver.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVolver.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVolver.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnVolver.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVolver.ForeColor = System.Drawing.Color.White;
            this.btnVolver.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnVolver.IconMarginLeft = 11;
            this.btnVolver.IconPadding = 10;
            this.btnVolver.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnVolver.IdleBorderColor = System.Drawing.Color.Red;
            this.btnVolver.IdleBorderRadius = 3;
            this.btnVolver.IdleBorderThickness = 1;
            this.btnVolver.IdleFillColor = System.Drawing.Color.Red;
            this.btnVolver.IdleIconLeftImage = null;
            this.btnVolver.IdleIconRightImage = null;
            this.btnVolver.IndicateFocus = false;
            this.btnVolver.Location = new System.Drawing.Point(1117, 500);
            this.btnVolver.Margin = new System.Windows.Forms.Padding(4);
            this.btnVolver.Name = "btnVolver";
            stateProperties45.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties45.BorderRadius = 3;
            stateProperties45.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties45.BorderThickness = 1;
            stateProperties45.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties45.ForeColor = System.Drawing.Color.White;
            stateProperties45.IconLeftImage = null;
            stateProperties45.IconRightImage = null;
            this.btnVolver.onHoverState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties46.BorderRadius = 3;
            stateProperties46.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties46.BorderThickness = 1;
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties46.ForeColor = System.Drawing.Color.White;
            stateProperties46.IconLeftImage = null;
            stateProperties46.IconRightImage = null;
            this.btnVolver.OnPressedState = stateProperties46;
            this.btnVolver.Size = new System.Drawing.Size(119, 55);
            this.btnVolver.TabIndex = 0;
            this.btnVolver.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVolver.TextMarginLeft = 0;
            this.btnVolver.UseDefaultRadiusAndThickness = true;
            this.btnVolver.Click += new System.EventHandler(this.btnVolver_Click);
            // 
            // btnGuardarCambios
            // 
            this.btnGuardarCambios.AllowToggling = false;
            this.btnGuardarCambios.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnGuardarCambios.AnimationSpeed = 200;
            this.btnGuardarCambios.AutoGenerateColors = false;
            this.btnGuardarCambios.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardarCambios.BackColor1 = System.Drawing.Color.LimeGreen;
            this.btnGuardarCambios.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardarCambios.BackgroundImage")));
            this.btnGuardarCambios.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardarCambios.ButtonText = "Guardar Cambios";
            this.btnGuardarCambios.ButtonTextMarginLeft = 0;
            this.btnGuardarCambios.ColorContrastOnClick = 45;
            this.btnGuardarCambios.ColorContrastOnHover = 45;
            this.btnGuardarCambios.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnGuardarCambios.CustomizableEdges = borderEdges6;
            this.btnGuardarCambios.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardarCambios.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnGuardarCambios.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarCambios.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarCambios.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGuardarCambios.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardarCambios.ForeColor = System.Drawing.Color.White;
            this.btnGuardarCambios.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnGuardarCambios.IconMarginLeft = 11;
            this.btnGuardarCambios.IconPadding = 10;
            this.btnGuardarCambios.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnGuardarCambios.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.btnGuardarCambios.IdleBorderRadius = 3;
            this.btnGuardarCambios.IdleBorderThickness = 1;
            this.btnGuardarCambios.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.btnGuardarCambios.IdleIconLeftImage = null;
            this.btnGuardarCambios.IdleIconRightImage = null;
            this.btnGuardarCambios.IndicateFocus = false;
            this.btnGuardarCambios.Location = new System.Drawing.Point(668, 466);
            this.btnGuardarCambios.Margin = new System.Windows.Forms.Padding(4);
            this.btnGuardarCambios.Name = "btnGuardarCambios";
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.BorderRadius = 3;
            stateProperties47.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties47.BorderThickness = 1;
            stateProperties47.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.ForeColor = System.Drawing.Color.White;
            stateProperties47.IconLeftImage = null;
            stateProperties47.IconRightImage = null;
            this.btnGuardarCambios.onHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties48.BorderRadius = 3;
            stateProperties48.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties48.BorderThickness = 1;
            stateProperties48.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties48.ForeColor = System.Drawing.Color.White;
            stateProperties48.IconLeftImage = null;
            stateProperties48.IconRightImage = null;
            this.btnGuardarCambios.OnPressedState = stateProperties48;
            this.btnGuardarCambios.Size = new System.Drawing.Size(175, 55);
            this.btnGuardarCambios.TabIndex = 0;
            this.btnGuardarCambios.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardarCambios.TextMarginLeft = 0;
            this.btnGuardarCambios.UseDefaultRadiusAndThickness = true;
            this.btnGuardarCambios.Click += new System.EventHandler(this.btnGuardarCambios_Click);
            // 
            // btnGuardar
            // 
            this.btnGuardar.AllowToggling = false;
            this.btnGuardar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnGuardar.AnimationSpeed = 200;
            this.btnGuardar.AutoGenerateColors = false;
            this.btnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardar.BackColor1 = System.Drawing.Color.LimeGreen;
            this.btnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardar.BackgroundImage")));
            this.btnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.ButtonText = "Guardar";
            this.btnGuardar.ButtonTextMarginLeft = 0;
            this.btnGuardar.ColorContrastOnClick = 45;
            this.btnGuardar.ColorContrastOnHover = 45;
            this.btnGuardar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnGuardar.CustomizableEdges = borderEdges7;
            this.btnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardar.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnGuardar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGuardar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnGuardar.IconMarginLeft = 11;
            this.btnGuardar.IconPadding = 10;
            this.btnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnGuardar.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.btnGuardar.IdleBorderRadius = 3;
            this.btnGuardar.IdleBorderThickness = 1;
            this.btnGuardar.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.btnGuardar.IdleIconLeftImage = null;
            this.btnGuardar.IdleIconRightImage = null;
            this.btnGuardar.IndicateFocus = false;
            this.btnGuardar.Location = new System.Drawing.Point(452, 466);
            this.btnGuardar.Margin = new System.Windows.Forms.Padding(4);
            this.btnGuardar.Name = "btnGuardar";
            stateProperties49.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties49.BorderRadius = 3;
            stateProperties49.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties49.BorderThickness = 1;
            stateProperties49.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties49.ForeColor = System.Drawing.Color.White;
            stateProperties49.IconLeftImage = null;
            stateProperties49.IconRightImage = null;
            this.btnGuardar.onHoverState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties50.BorderRadius = 3;
            stateProperties50.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties50.BorderThickness = 1;
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties50.ForeColor = System.Drawing.Color.White;
            stateProperties50.IconLeftImage = null;
            stateProperties50.IconRightImage = null;
            this.btnGuardar.OnPressedState = stateProperties50;
            this.btnGuardar.Size = new System.Drawing.Size(175, 55);
            this.btnGuardar.TabIndex = 0;
            this.btnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardar.TextMarginLeft = 0;
            this.btnGuardar.UseDefaultRadiusAndThickness = true;
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click);
            // 
            // txtProvincia
            // 
            this.txtProvincia.AcceptsReturn = false;
            this.txtProvincia.AcceptsTab = false;
            this.txtProvincia.AnimationSpeed = 200;
            this.txtProvincia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtProvincia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtProvincia.BackColor = System.Drawing.Color.Transparent;
            this.txtProvincia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtProvincia.BackgroundImage")));
            this.txtProvincia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtProvincia.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtProvincia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtProvincia.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtProvincia.BorderRadius = 1;
            this.txtProvincia.BorderThickness = 1;
            this.txtProvincia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtProvincia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProvincia.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtProvincia.DefaultText = "";
            this.txtProvincia.FillColor = System.Drawing.Color.White;
            this.txtProvincia.HideSelection = true;
            this.txtProvincia.IconLeft = null;
            this.txtProvincia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProvincia.IconPadding = 10;
            this.txtProvincia.IconRight = null;
            this.txtProvincia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProvincia.Lines = new string[0];
            this.txtProvincia.Location = new System.Drawing.Point(380, 342);
            this.txtProvincia.Margin = new System.Windows.Forms.Padding(4);
            this.txtProvincia.MaxLength = 32767;
            this.txtProvincia.MinimumSize = new System.Drawing.Size(133, 43);
            this.txtProvincia.Modified = false;
            this.txtProvincia.Multiline = false;
            this.txtProvincia.Name = "txtProvincia";
            stateProperties51.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProvincia.OnActiveState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Empty;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProvincia.OnDisabledState = stateProperties52;
            stateProperties53.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProvincia.OnHoverState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.Silver;
            stateProperties54.FillColor = System.Drawing.Color.White;
            stateProperties54.ForeColor = System.Drawing.Color.Empty;
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProvincia.OnIdleState = stateProperties54;
            this.txtProvincia.PasswordChar = '\0';
            this.txtProvincia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProvincia.PlaceholderText = "";
            this.txtProvincia.ReadOnly = false;
            this.txtProvincia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtProvincia.SelectedText = "";
            this.txtProvincia.SelectionLength = 0;
            this.txtProvincia.SelectionStart = 0;
            this.txtProvincia.ShortcutsEnabled = true;
            this.txtProvincia.Size = new System.Drawing.Size(349, 43);
            this.txtProvincia.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtProvincia.TabIndex = 2;
            this.txtProvincia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtProvincia.TextMarginBottom = 0;
            this.txtProvincia.TextMarginLeft = 5;
            this.txtProvincia.TextMarginTop = 0;
            this.txtProvincia.TextPlaceholder = "";
            this.txtProvincia.UseSystemPasswordChar = false;
            this.txtProvincia.WordWrap = true;
            // 
            // txtCorreo
            // 
            this.txtCorreo.AcceptsReturn = false;
            this.txtCorreo.AcceptsTab = false;
            this.txtCorreo.AnimationSpeed = 200;
            this.txtCorreo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCorreo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCorreo.BackColor = System.Drawing.Color.Transparent;
            this.txtCorreo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCorreo.BackgroundImage")));
            this.txtCorreo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCorreo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtCorreo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCorreo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCorreo.BorderRadius = 1;
            this.txtCorreo.BorderThickness = 1;
            this.txtCorreo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCorreo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtCorreo.DefaultText = "";
            this.txtCorreo.FillColor = System.Drawing.Color.White;
            this.txtCorreo.HideSelection = true;
            this.txtCorreo.IconLeft = null;
            this.txtCorreo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.IconPadding = 10;
            this.txtCorreo.IconRight = null;
            this.txtCorreo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.Lines = new string[0];
            this.txtCorreo.Location = new System.Drawing.Point(867, 149);
            this.txtCorreo.Margin = new System.Windows.Forms.Padding(4);
            this.txtCorreo.MaxLength = 32767;
            this.txtCorreo.MinimumSize = new System.Drawing.Size(133, 43);
            this.txtCorreo.Modified = false;
            this.txtCorreo.Multiline = false;
            this.txtCorreo.Name = "txtCorreo";
            stateProperties55.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreo.OnActiveState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Empty;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCorreo.OnDisabledState = stateProperties56;
            stateProperties57.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreo.OnHoverState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.Silver;
            stateProperties58.FillColor = System.Drawing.Color.White;
            stateProperties58.ForeColor = System.Drawing.Color.Empty;
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreo.OnIdleState = stateProperties58;
            this.txtCorreo.PasswordChar = '\0';
            this.txtCorreo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCorreo.PlaceholderText = "";
            this.txtCorreo.ReadOnly = false;
            this.txtCorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCorreo.SelectedText = "";
            this.txtCorreo.SelectionLength = 0;
            this.txtCorreo.SelectionStart = 0;
            this.txtCorreo.ShortcutsEnabled = true;
            this.txtCorreo.Size = new System.Drawing.Size(349, 43);
            this.txtCorreo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtCorreo.TabIndex = 2;
            this.txtCorreo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCorreo.TextMarginBottom = 0;
            this.txtCorreo.TextMarginLeft = 5;
            this.txtCorreo.TextMarginTop = 0;
            this.txtCorreo.TextPlaceholder = "";
            this.txtCorreo.UseSystemPasswordChar = false;
            this.txtCorreo.WordWrap = true;
            // 
            // txtTelefono
            // 
            this.txtTelefono.AcceptsReturn = false;
            this.txtTelefono.AcceptsTab = false;
            this.txtTelefono.AnimationSpeed = 200;
            this.txtTelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefono.BackColor = System.Drawing.Color.Transparent;
            this.txtTelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefono.BackgroundImage")));
            this.txtTelefono.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtTelefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTelefono.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTelefono.BorderRadius = 1;
            this.txtTelefono.BorderThickness = 1;
            this.txtTelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtTelefono.DefaultText = "";
            this.txtTelefono.FillColor = System.Drawing.Color.White;
            this.txtTelefono.HideSelection = true;
            this.txtTelefono.IconLeft = null;
            this.txtTelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.IconPadding = 10;
            this.txtTelefono.IconRight = null;
            this.txtTelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.Lines = new string[0];
            this.txtTelefono.Location = new System.Drawing.Point(867, 52);
            this.txtTelefono.Margin = new System.Windows.Forms.Padding(4);
            this.txtTelefono.MaxLength = 32767;
            this.txtTelefono.MinimumSize = new System.Drawing.Size(133, 43);
            this.txtTelefono.Modified = false;
            this.txtTelefono.Multiline = false;
            this.txtTelefono.Name = "txtTelefono";
            stateProperties59.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnActiveState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Empty;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefono.OnDisabledState = stateProperties60;
            stateProperties61.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnHoverState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.Silver;
            stateProperties62.FillColor = System.Drawing.Color.White;
            stateProperties62.ForeColor = System.Drawing.Color.Empty;
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnIdleState = stateProperties62;
            this.txtTelefono.PasswordChar = '\0';
            this.txtTelefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefono.PlaceholderText = "";
            this.txtTelefono.ReadOnly = false;
            this.txtTelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefono.SelectedText = "";
            this.txtTelefono.SelectionLength = 0;
            this.txtTelefono.SelectionStart = 0;
            this.txtTelefono.ShortcutsEnabled = true;
            this.txtTelefono.Size = new System.Drawing.Size(349, 43);
            this.txtTelefono.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtTelefono.TabIndex = 2;
            this.txtTelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefono.TextMarginBottom = 0;
            this.txtTelefono.TextMarginLeft = 5;
            this.txtTelefono.TextMarginTop = 0;
            this.txtTelefono.TextPlaceholder = "";
            this.txtTelefono.UseSystemPasswordChar = false;
            this.txtTelefono.WordWrap = true;
            // 
            // txtZona
            // 
            this.txtZona.AcceptsReturn = false;
            this.txtZona.AcceptsTab = false;
            this.txtZona.AnimationSpeed = 200;
            this.txtZona.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtZona.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtZona.BackColor = System.Drawing.Color.Transparent;
            this.txtZona.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtZona.BackgroundImage")));
            this.txtZona.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtZona.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtZona.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtZona.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtZona.BorderRadius = 1;
            this.txtZona.BorderThickness = 1;
            this.txtZona.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtZona.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtZona.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtZona.DefaultText = "";
            this.txtZona.FillColor = System.Drawing.Color.White;
            this.txtZona.HideSelection = true;
            this.txtZona.IconLeft = null;
            this.txtZona.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtZona.IconPadding = 10;
            this.txtZona.IconRight = null;
            this.txtZona.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtZona.Lines = new string[0];
            this.txtZona.Location = new System.Drawing.Point(479, 149);
            this.txtZona.Margin = new System.Windows.Forms.Padding(4);
            this.txtZona.MaxLength = 32767;
            this.txtZona.MinimumSize = new System.Drawing.Size(133, 43);
            this.txtZona.Modified = false;
            this.txtZona.Multiline = false;
            this.txtZona.Name = "txtZona";
            stateProperties63.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtZona.OnActiveState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Empty;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtZona.OnDisabledState = stateProperties64;
            stateProperties65.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties65.FillColor = System.Drawing.Color.Empty;
            stateProperties65.ForeColor = System.Drawing.Color.Empty;
            stateProperties65.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtZona.OnHoverState = stateProperties65;
            stateProperties66.BorderColor = System.Drawing.Color.Silver;
            stateProperties66.FillColor = System.Drawing.Color.White;
            stateProperties66.ForeColor = System.Drawing.Color.Empty;
            stateProperties66.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtZona.OnIdleState = stateProperties66;
            this.txtZona.PasswordChar = '\0';
            this.txtZona.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtZona.PlaceholderText = "";
            this.txtZona.ReadOnly = false;
            this.txtZona.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtZona.SelectedText = "";
            this.txtZona.SelectionLength = 0;
            this.txtZona.SelectionStart = 0;
            this.txtZona.ShortcutsEnabled = true;
            this.txtZona.Size = new System.Drawing.Size(349, 43);
            this.txtZona.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtZona.TabIndex = 2;
            this.txtZona.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtZona.TextMarginBottom = 0;
            this.txtZona.TextMarginLeft = 5;
            this.txtZona.TextMarginTop = 0;
            this.txtZona.TextPlaceholder = "";
            this.txtZona.UseSystemPasswordChar = false;
            this.txtZona.WordWrap = true;
            // 
            // txtDireccion
            // 
            this.txtDireccion.AcceptsReturn = false;
            this.txtDireccion.AcceptsTab = false;
            this.txtDireccion.AnimationSpeed = 200;
            this.txtDireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDireccion.BackColor = System.Drawing.Color.Transparent;
            this.txtDireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDireccion.BackgroundImage")));
            this.txtDireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDireccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDireccion.BorderRadius = 1;
            this.txtDireccion.BorderThickness = 1;
            this.txtDireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDireccion.DefaultText = "";
            this.txtDireccion.FillColor = System.Drawing.Color.White;
            this.txtDireccion.HideSelection = true;
            this.txtDireccion.IconLeft = null;
            this.txtDireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.IconPadding = 10;
            this.txtDireccion.IconRight = null;
            this.txtDireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.Lines = new string[0];
            this.txtDireccion.Location = new System.Drawing.Point(64, 251);
            this.txtDireccion.Margin = new System.Windows.Forms.Padding(4);
            this.txtDireccion.MaxLength = 32767;
            this.txtDireccion.MinimumSize = new System.Drawing.Size(133, 43);
            this.txtDireccion.Modified = false;
            this.txtDireccion.Multiline = false;
            this.txtDireccion.Name = "txtDireccion";
            stateProperties67.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties67.FillColor = System.Drawing.Color.Empty;
            stateProperties67.ForeColor = System.Drawing.Color.Empty;
            stateProperties67.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnActiveState = stateProperties67;
            stateProperties68.BorderColor = System.Drawing.Color.Empty;
            stateProperties68.FillColor = System.Drawing.Color.White;
            stateProperties68.ForeColor = System.Drawing.Color.Empty;
            stateProperties68.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDireccion.OnDisabledState = stateProperties68;
            stateProperties69.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties69.FillColor = System.Drawing.Color.Empty;
            stateProperties69.ForeColor = System.Drawing.Color.Empty;
            stateProperties69.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnHoverState = stateProperties69;
            stateProperties70.BorderColor = System.Drawing.Color.Silver;
            stateProperties70.FillColor = System.Drawing.Color.White;
            stateProperties70.ForeColor = System.Drawing.Color.Empty;
            stateProperties70.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnIdleState = stateProperties70;
            this.txtDireccion.PasswordChar = '\0';
            this.txtDireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDireccion.PlaceholderText = "";
            this.txtDireccion.ReadOnly = false;
            this.txtDireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDireccion.SelectedText = "";
            this.txtDireccion.SelectionLength = 0;
            this.txtDireccion.SelectionStart = 0;
            this.txtDireccion.ShortcutsEnabled = true;
            this.txtDireccion.Size = new System.Drawing.Size(762, 43);
            this.txtDireccion.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDireccion.TabIndex = 2;
            this.txtDireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDireccion.TextMarginBottom = 0;
            this.txtDireccion.TextMarginLeft = 5;
            this.txtDireccion.TextMarginTop = 0;
            this.txtDireccion.TextPlaceholder = "";
            this.txtDireccion.UseSystemPasswordChar = false;
            this.txtDireccion.WordWrap = true;
            // 
            // txtCanton
            // 
            this.txtCanton.AcceptsReturn = false;
            this.txtCanton.AcceptsTab = false;
            this.txtCanton.AnimationSpeed = 200;
            this.txtCanton.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCanton.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCanton.BackColor = System.Drawing.Color.Transparent;
            this.txtCanton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCanton.BackgroundImage")));
            this.txtCanton.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCanton.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtCanton.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCanton.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCanton.BorderRadius = 1;
            this.txtCanton.BorderThickness = 1;
            this.txtCanton.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCanton.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCanton.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtCanton.DefaultText = "";
            this.txtCanton.FillColor = System.Drawing.Color.White;
            this.txtCanton.HideSelection = true;
            this.txtCanton.IconLeft = null;
            this.txtCanton.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCanton.IconPadding = 10;
            this.txtCanton.IconRight = null;
            this.txtCanton.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCanton.Lines = new string[0];
            this.txtCanton.Location = new System.Drawing.Point(867, 251);
            this.txtCanton.Margin = new System.Windows.Forms.Padding(4);
            this.txtCanton.MaxLength = 32767;
            this.txtCanton.MinimumSize = new System.Drawing.Size(133, 43);
            this.txtCanton.Modified = false;
            this.txtCanton.Multiline = false;
            this.txtCanton.Name = "txtCanton";
            stateProperties71.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties71.FillColor = System.Drawing.Color.Empty;
            stateProperties71.ForeColor = System.Drawing.Color.Empty;
            stateProperties71.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCanton.OnActiveState = stateProperties71;
            stateProperties72.BorderColor = System.Drawing.Color.Empty;
            stateProperties72.FillColor = System.Drawing.Color.White;
            stateProperties72.ForeColor = System.Drawing.Color.Empty;
            stateProperties72.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCanton.OnDisabledState = stateProperties72;
            stateProperties73.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties73.FillColor = System.Drawing.Color.Empty;
            stateProperties73.ForeColor = System.Drawing.Color.Empty;
            stateProperties73.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCanton.OnHoverState = stateProperties73;
            stateProperties74.BorderColor = System.Drawing.Color.Silver;
            stateProperties74.FillColor = System.Drawing.Color.White;
            stateProperties74.ForeColor = System.Drawing.Color.Empty;
            stateProperties74.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCanton.OnIdleState = stateProperties74;
            this.txtCanton.PasswordChar = '\0';
            this.txtCanton.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCanton.PlaceholderText = "";
            this.txtCanton.ReadOnly = false;
            this.txtCanton.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCanton.SelectedText = "";
            this.txtCanton.SelectionLength = 0;
            this.txtCanton.SelectionStart = 0;
            this.txtCanton.ShortcutsEnabled = true;
            this.txtCanton.Size = new System.Drawing.Size(349, 43);
            this.txtCanton.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtCanton.TabIndex = 2;
            this.txtCanton.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCanton.TextMarginBottom = 0;
            this.txtCanton.TextMarginLeft = 5;
            this.txtCanton.TextMarginTop = 0;
            this.txtCanton.TextPlaceholder = "";
            this.txtCanton.UseSystemPasswordChar = false;
            this.txtCanton.WordWrap = true;
            // 
            // txtParroquia
            // 
            this.txtParroquia.AcceptsReturn = false;
            this.txtParroquia.AcceptsTab = false;
            this.txtParroquia.AnimationSpeed = 200;
            this.txtParroquia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtParroquia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtParroquia.BackColor = System.Drawing.Color.Transparent;
            this.txtParroquia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtParroquia.BackgroundImage")));
            this.txtParroquia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtParroquia.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtParroquia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtParroquia.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtParroquia.BorderRadius = 1;
            this.txtParroquia.BorderThickness = 1;
            this.txtParroquia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtParroquia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParroquia.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtParroquia.DefaultText = "";
            this.txtParroquia.FillColor = System.Drawing.Color.White;
            this.txtParroquia.HideSelection = true;
            this.txtParroquia.IconLeft = null;
            this.txtParroquia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParroquia.IconPadding = 10;
            this.txtParroquia.IconRight = null;
            this.txtParroquia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParroquia.Lines = new string[0];
            this.txtParroquia.Location = new System.Drawing.Point(774, 342);
            this.txtParroquia.Margin = new System.Windows.Forms.Padding(4);
            this.txtParroquia.MaxLength = 32767;
            this.txtParroquia.MinimumSize = new System.Drawing.Size(133, 43);
            this.txtParroquia.Modified = false;
            this.txtParroquia.Multiline = false;
            this.txtParroquia.Name = "txtParroquia";
            stateProperties75.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties75.FillColor = System.Drawing.Color.Empty;
            stateProperties75.ForeColor = System.Drawing.Color.Empty;
            stateProperties75.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParroquia.OnActiveState = stateProperties75;
            stateProperties76.BorderColor = System.Drawing.Color.Empty;
            stateProperties76.FillColor = System.Drawing.Color.White;
            stateProperties76.ForeColor = System.Drawing.Color.Empty;
            stateProperties76.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtParroquia.OnDisabledState = stateProperties76;
            stateProperties77.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties77.FillColor = System.Drawing.Color.Empty;
            stateProperties77.ForeColor = System.Drawing.Color.Empty;
            stateProperties77.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParroquia.OnHoverState = stateProperties77;
            stateProperties78.BorderColor = System.Drawing.Color.Silver;
            stateProperties78.FillColor = System.Drawing.Color.White;
            stateProperties78.ForeColor = System.Drawing.Color.Empty;
            stateProperties78.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParroquia.OnIdleState = stateProperties78;
            this.txtParroquia.PasswordChar = '\0';
            this.txtParroquia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtParroquia.PlaceholderText = "";
            this.txtParroquia.ReadOnly = false;
            this.txtParroquia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtParroquia.SelectedText = "";
            this.txtParroquia.SelectionLength = 0;
            this.txtParroquia.SelectionStart = 0;
            this.txtParroquia.ShortcutsEnabled = true;
            this.txtParroquia.Size = new System.Drawing.Size(349, 43);
            this.txtParroquia.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtParroquia.TabIndex = 2;
            this.txtParroquia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtParroquia.TextMarginBottom = 0;
            this.txtParroquia.TextMarginLeft = 5;
            this.txtParroquia.TextMarginTop = 0;
            this.txtParroquia.TextPlaceholder = "";
            this.txtParroquia.UseSystemPasswordChar = false;
            this.txtParroquia.WordWrap = true;
            // 
            // txtCodIess
            // 
            this.txtCodIess.AcceptsReturn = false;
            this.txtCodIess.AcceptsTab = false;
            this.txtCodIess.AnimationSpeed = 200;
            this.txtCodIess.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCodIess.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCodIess.BackColor = System.Drawing.Color.Transparent;
            this.txtCodIess.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCodIess.BackgroundImage")));
            this.txtCodIess.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCodIess.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtCodIess.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCodIess.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCodIess.BorderRadius = 1;
            this.txtCodIess.BorderThickness = 1;
            this.txtCodIess.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCodIess.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodIess.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtCodIess.DefaultText = "";
            this.txtCodIess.FillColor = System.Drawing.Color.White;
            this.txtCodIess.HideSelection = true;
            this.txtCodIess.IconLeft = null;
            this.txtCodIess.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodIess.IconPadding = 10;
            this.txtCodIess.IconRight = null;
            this.txtCodIess.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodIess.Lines = new string[0];
            this.txtCodIess.Location = new System.Drawing.Point(64, 149);
            this.txtCodIess.Margin = new System.Windows.Forms.Padding(4);
            this.txtCodIess.MaxLength = 32767;
            this.txtCodIess.MinimumSize = new System.Drawing.Size(133, 43);
            this.txtCodIess.Modified = false;
            this.txtCodIess.Multiline = false;
            this.txtCodIess.Name = "txtCodIess";
            stateProperties79.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties79.FillColor = System.Drawing.Color.Empty;
            stateProperties79.ForeColor = System.Drawing.Color.Empty;
            stateProperties79.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodIess.OnActiveState = stateProperties79;
            stateProperties80.BorderColor = System.Drawing.Color.Empty;
            stateProperties80.FillColor = System.Drawing.Color.White;
            stateProperties80.ForeColor = System.Drawing.Color.Empty;
            stateProperties80.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCodIess.OnDisabledState = stateProperties80;
            stateProperties81.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties81.FillColor = System.Drawing.Color.Empty;
            stateProperties81.ForeColor = System.Drawing.Color.Empty;
            stateProperties81.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodIess.OnHoverState = stateProperties81;
            stateProperties82.BorderColor = System.Drawing.Color.Silver;
            stateProperties82.FillColor = System.Drawing.Color.White;
            stateProperties82.ForeColor = System.Drawing.Color.Empty;
            stateProperties82.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodIess.OnIdleState = stateProperties82;
            this.txtCodIess.PasswordChar = '\0';
            this.txtCodIess.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCodIess.PlaceholderText = "";
            this.txtCodIess.ReadOnly = false;
            this.txtCodIess.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCodIess.SelectedText = "";
            this.txtCodIess.SelectionLength = 0;
            this.txtCodIess.SelectionStart = 0;
            this.txtCodIess.ShortcutsEnabled = true;
            this.txtCodIess.Size = new System.Drawing.Size(349, 43);
            this.txtCodIess.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtCodIess.TabIndex = 2;
            this.txtCodIess.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCodIess.TextMarginBottom = 0;
            this.txtCodIess.TextMarginLeft = 5;
            this.txtCodIess.TextMarginTop = 0;
            this.txtCodIess.TextPlaceholder = "";
            this.txtCodIess.UseSystemPasswordChar = false;
            this.txtCodIess.WordWrap = true;
            // 
            // txtNombre
            // 
            this.txtNombre.AcceptsReturn = false;
            this.txtNombre.AcceptsTab = false;
            this.txtNombre.AnimationSpeed = 200;
            this.txtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombre.BackgroundImage")));
            this.txtNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNombre.BorderRadius = 1;
            this.txtNombre.BorderThickness = 1;
            this.txtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtNombre.DefaultText = "";
            this.txtNombre.FillColor = System.Drawing.Color.White;
            this.txtNombre.HideSelection = true;
            this.txtNombre.IconLeft = null;
            this.txtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.IconPadding = 10;
            this.txtNombre.IconRight = null;
            this.txtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.Lines = new string[0];
            this.txtNombre.Location = new System.Drawing.Point(64, 52);
            this.txtNombre.Margin = new System.Windows.Forms.Padding(4);
            this.txtNombre.MaxLength = 32767;
            this.txtNombre.MinimumSize = new System.Drawing.Size(133, 43);
            this.txtNombre.Modified = false;
            this.txtNombre.Multiline = false;
            this.txtNombre.Name = "txtNombre";
            stateProperties83.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties83.FillColor = System.Drawing.Color.Empty;
            stateProperties83.ForeColor = System.Drawing.Color.Empty;
            stateProperties83.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnActiveState = stateProperties83;
            stateProperties84.BorderColor = System.Drawing.Color.Empty;
            stateProperties84.FillColor = System.Drawing.Color.White;
            stateProperties84.ForeColor = System.Drawing.Color.Empty;
            stateProperties84.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombre.OnDisabledState = stateProperties84;
            stateProperties85.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties85.FillColor = System.Drawing.Color.Empty;
            stateProperties85.ForeColor = System.Drawing.Color.Empty;
            stateProperties85.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnHoverState = stateProperties85;
            stateProperties86.BorderColor = System.Drawing.Color.Silver;
            stateProperties86.FillColor = System.Drawing.Color.White;
            stateProperties86.ForeColor = System.Drawing.Color.Empty;
            stateProperties86.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnIdleState = stateProperties86;
            this.txtNombre.PasswordChar = '\0';
            this.txtNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombre.PlaceholderText = "";
            this.txtNombre.ReadOnly = false;
            this.txtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombre.SelectedText = "";
            this.txtNombre.SelectionLength = 0;
            this.txtNombre.SelectionStart = 0;
            this.txtNombre.ShortcutsEnabled = true;
            this.txtNombre.Size = new System.Drawing.Size(762, 43);
            this.txtNombre.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtNombre.TabIndex = 2;
            this.txtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombre.TextMarginBottom = 0;
            this.txtNombre.TextMarginLeft = 5;
            this.txtNombre.TextMarginTop = 0;
            this.txtNombre.TextPlaceholder = "";
            this.txtNombre.UseSystemPasswordChar = false;
            this.txtNombre.WordWrap = true;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(375, 310);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(96, 28);
            this.label2.TabIndex = 1;
            this.label2.Text = "Provincia:";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(862, 117);
            this.label6.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(76, 28);
            this.label6.TabIndex = 1;
            this.label6.Text = "Correo:";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(862, 20);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(90, 28);
            this.label5.TabIndex = 1;
            this.label5.Text = "Telefono:";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(59, 319);
            this.label7.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(220, 28);
            this.label7.TabIndex = 1;
            this.label7.Text = "Tipo de Financiamiento:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(474, 117);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(60, 28);
            this.label4.TabIndex = 1;
            this.label4.Text = "Zona:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(59, 219);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(98, 28);
            this.label3.TabIndex = 1;
            this.label3.Text = "Direccion:";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(862, 219);
            this.label8.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(79, 28);
            this.label8.TabIndex = 1;
            this.label8.Text = "Canton:";
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(769, 310);
            this.label14.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(100, 28);
            this.label14.TabIndex = 1;
            this.label14.Text = "Parroquia:";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(59, 117);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(119, 28);
            this.label1.TabIndex = 1;
            this.label1.Text = "Codigo IESS";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(59, 20);
            this.label10.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(237, 28);
            this.label10.TabIndex = 1;
            this.label10.Text = "Nombre de la Institución :";
            this.label10.Click += new System.EventHandler(this.label10_Click);
            // 
            // dataGridUsuarios
            // 
            this.dataGridUsuarios.AllowCustomTheming = false;
            this.dataGridUsuarios.AllowUserToAddRows = false;
            this.dataGridUsuarios.AllowUserToDeleteRows = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.dataGridUsuarios.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dataGridUsuarios.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells;
            this.dataGridUsuarios.BackgroundColor = System.Drawing.Color.White;
            this.dataGridUsuarios.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridUsuarios.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridUsuarios.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridUsuarios.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dataGridUsuarios.ColumnHeadersHeight = 40;
            this.dataGridUsuarios.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.eliminar});
            this.dataGridUsuarios.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dataGridUsuarios.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridUsuarios.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridUsuarios.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridUsuarios.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataGridUsuarios.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dataGridUsuarios.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridUsuarios.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridUsuarios.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataGridUsuarios.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataGridUsuarios.CurrentTheme.Name = null;
            this.dataGridUsuarios.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataGridUsuarios.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridUsuarios.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridUsuarios.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridUsuarios.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridUsuarios.DefaultCellStyle = dataGridViewCellStyle6;
            this.dataGridUsuarios.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataGridUsuarios.EnableHeadersVisualStyles = false;
            this.dataGridUsuarios.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridUsuarios.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridUsuarios.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataGridUsuarios.HeaderForeColor = System.Drawing.Color.White;
            this.dataGridUsuarios.Location = new System.Drawing.Point(0, 85);
            this.dataGridUsuarios.Name = "dataGridUsuarios";
            this.dataGridUsuarios.ReadOnly = true;
            this.dataGridUsuarios.RowHeadersVisible = false;
            this.dataGridUsuarios.RowHeadersWidth = 51;
            this.dataGridUsuarios.RowTemplate.Height = 40;
            this.dataGridUsuarios.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridUsuarios.Size = new System.Drawing.Size(1404, 631);
            this.dataGridUsuarios.TabIndex = 5;
            this.dataGridUsuarios.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dataGridUsuarios.CellContentDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridUsuarios_CellContentDoubleClick);
            this.dataGridUsuarios.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridUsuarios_CellDoubleClick);
            this.dataGridUsuarios.DataError += new System.Windows.Forms.DataGridViewDataErrorEventHandler(this.dataGridUsuarios_DataError);
            // 
            // eliminar
            // 
            this.eliminar.HeaderText = "";
            this.eliminar.Image = ((System.Drawing.Image)(resources.GetObject("eliminar.Image")));
            this.eliminar.ImageLayout = System.Windows.Forms.DataGridViewImageCellLayout.Zoom;
            this.eliminar.MinimumWidth = 6;
            this.eliminar.Name = "eliminar";
            this.eliminar.ReadOnly = true;
            this.eliminar.Width = 6;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.btnNuevo);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1404, 85);
            this.panel1.TabIndex = 6;
            // 
            // btnNuevo
            // 
            this.btnNuevo.AllowToggling = false;
            this.btnNuevo.AnimationSpeed = 200;
            this.btnNuevo.AutoGenerateColors = false;
            this.btnNuevo.BackColor = System.Drawing.Color.Transparent;
            this.btnNuevo.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnNuevo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNuevo.BackgroundImage")));
            this.btnNuevo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNuevo.ButtonText = "Nuevo";
            this.btnNuevo.ButtonTextMarginLeft = 0;
            this.btnNuevo.ColorContrastOnClick = 45;
            this.btnNuevo.ColorContrastOnHover = 45;
            this.btnNuevo.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnNuevo.CustomizableEdges = borderEdges8;
            this.btnNuevo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNuevo.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnNuevo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNuevo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNuevo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNuevo.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNuevo.ForeColor = System.Drawing.Color.White;
            this.btnNuevo.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnNuevo.IconMarginLeft = 11;
            this.btnNuevo.IconPadding = 10;
            this.btnNuevo.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnNuevo.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnNuevo.IdleBorderRadius = 3;
            this.btnNuevo.IdleBorderThickness = 1;
            this.btnNuevo.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnNuevo.IdleIconLeftImage = null;
            this.btnNuevo.IdleIconRightImage = null;
            this.btnNuevo.IndicateFocus = false;
            this.btnNuevo.Location = new System.Drawing.Point(13, 13);
            this.btnNuevo.Margin = new System.Windows.Forms.Padding(4);
            this.btnNuevo.Name = "btnNuevo";
            stateProperties87.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties87.BorderRadius = 3;
            stateProperties87.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties87.BorderThickness = 1;
            stateProperties87.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties87.ForeColor = System.Drawing.Color.White;
            stateProperties87.IconLeftImage = null;
            stateProperties87.IconRightImage = null;
            this.btnNuevo.onHoverState = stateProperties87;
            stateProperties88.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties88.BorderRadius = 3;
            stateProperties88.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties88.BorderThickness = 1;
            stateProperties88.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties88.ForeColor = System.Drawing.Color.White;
            stateProperties88.IconLeftImage = null;
            stateProperties88.IconRightImage = null;
            this.btnNuevo.OnPressedState = stateProperties88;
            this.btnNuevo.Size = new System.Drawing.Size(154, 48);
            this.btnNuevo.TabIndex = 1;
            this.btnNuevo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNuevo.TextMarginLeft = 0;
            this.btnNuevo.UseDefaultRadiusAndThickness = true;
            this.btnNuevo.Click += new System.EventHandler(this.btnNuevo_Click);
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // Instituto
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1404, 716);
            this.Controls.Add(this.panelUsuarios);
            this.Controls.Add(this.dataGridUsuarios);
            this.Controls.Add(this.panel1);
            this.Name = "Instituto";
            this.Text = "Instituto";
            this.Load += new System.EventHandler(this.Instituto_Load);
            this.panelUsuarios.ResumeLayout(false);
            this.panelUsuarios.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridUsuarios)).EndInit();
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel panelUsuarios;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label lblId;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnVolver;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGuardarCambios;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGuardar;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtParroquia;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtNombre;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label10;
        private Bunifu.UI.WinForms.BunifuDataGridView dataGridUsuarios;
        private System.Windows.Forms.DataGridViewImageColumn eliminar;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNuevo;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtCodIess;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtProvincia;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtCorreo;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtTelefono;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDireccion;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuDropdown dropFinaciamiento;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtZona;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtCanton;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.ErrorProvider errorProvider1;
    }
}